language: node_js
cache: yarn
script:
  - yarn --version
  - yarn check --integrity
  - yarn install
  - yarn setup
  - yarn lint
  - yarn test:nsp-warn
  - yarn test
#  - yarn test:routes
#  - yarn test:a11y
  - yarn test:coverage
after_success:
  - yarn test:codacy-upload
  - yarn test:codecov-upload
